main:
  - name: Home
    url: #
    params:
      icon:
        vendor: lingerieindonesia
        name: lingerieindonesia
  - name: Privacy Policy
    url: /privacy-policy.html
    params:
      icon:
        vendor: lingerieindonesia
        name: lingerieindonesia


