description: Razon Yang's start page.

hb:
  logo: images/logo.png
  header:
    socials:
      github: bajudinasmalam
      paypal: lingerieindonesia
      kofi: lingerieindonesia
  # theme_start:
    # search_engines:
    #   google:
    #     weight: 1
    #   bing:
    #     weight: 2
    #   baidu:
    #     weight: 3
    #   duckduckgo:
    #     weight: 4
    #   wikipedia:
    #     disable: false
    #   yahoo:
    #     disable: false
    #   yandex:
    #     disable: false
    #   sogou:
    #     disable: false

seo:
  favicons:
    icon: images/logo.png
