description: Jual Baju Dinas Malam Lingerie Bikini Kostum Halloween Terlengkap Terbaru dan Terbaik se indonesia dan kota medan.

hb:
  logo: images/logo.png
  header:
    socials:
      pinterest: lingerieindonesia
      facebook: lingerieindonesia
      instagram: lingerieindonesia
  theme_start:
    search_input_text: bajudinasmalam.id
hugopress:
   modules:
    custom:
      hooks:
        head-end:
          disable: false
  # theme_start:
    # search_engines:
    #   google:
    #     weight: 1
    #   bing:
    #     weight: 2
    #   baidu:
    #     weight: 3
    #   duckduckgo:
    #     weight: 4
    #   wikipedia:
    #     disable: false
    #   yahoo:
    #     disable: false
    #   yandex:
    #     disable: false
    #   sogou:
    #     disable: false

seo:
  favicons:
    icon: images/logo.png
