[build]
command = "npm ci && hugo --minify --gc -b $URL"
publish = "public"

[build.environment]
NODE_VERSION = "19"
HUGO_VERSION = "0.121.1"
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
GO_VERSION = "1.21"

[[headers]]
  for = "/*"
  [headers.values]
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "deny"
    X-XSS-Protection = "1; mode=block"
